version: "3.7"

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./db-data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dbpass

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: dbpass

  backend:
    build:
      context: ./backend
    ports:
      - 5000:5000
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    restart: always
