version: "3.7"

services:
  mongo:
    image: mongo
    restart: on-failure
    volumes:
      - ./db-data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dbpass

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: dbpass

  backend:
    build:
      context: ./backend
    ports:
      - 5000:5000
    restart: on-failure
    environment:
      MONGO_HOST: "192.168.11.127"

  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    restart: on-failure
    environment:
      REACT_APP_BACKEND_PORT: 5000
      REACT_APP_BACKEND_HOST: "127.0.0.1"
      REACT_APP_CSCO_API_HOST: "127.0.0.1"

  nginx:
    build: ./nginx
    ports:
      - 8888:8080
    restart: always
